### ISSUE TITLE
Uncaught exception during initial migration

### ISSUE THREAD

**Issue by msarabi95** [Zahajamaan/Fudulbank#2]
This what I get when running migrations for the first time.
I'm using macOS 10.13.4 and running Python 3.6.3.

    $ python manage.py migrate
    Operations to perform:
      Apply all migrations: accounts, admin, auth, contenttypes, core, easy_thumbnails, exams, guardian, mailer, notifications, post_office, sessions, silk, sites, teams, userena
    Running migrations:
    Applying contenttypes.0001_initial... OK
    Applying auth.0001_initial... OK
    Applying accounts.0001_initial... OK
    Applying exams.0001_initial... OK
    Applying exams.0002_add_categories_and_exams... OK
    Applying exams.0003_update_status... OK
    Applying exams.0004_add_status_choices... OK
    Applying exams.0005_is_first... OK
    Applying exams.0006_fill_is_first... OK
    Applying exams.0005_move_images_to_revision... OK
    Applying exams.0007_merge_20170617_0510... OK
    Applying exams.0008_is_last... OK
    Applying exams.0009_fill_is_last... OK
    Applying exams.0010_add_parent_question... OK
    Applying exams.0011_status_model... OK
    Applying exams.0012_add_statuses... OK
    Applying exams.0013_change_blanks... OK
    Applying exams.0014_revision_statuses... OK
    Applying exams.0015_move_statuses_to_revision... OK
    Applying exams.0016_remove_status... OK
    Applying exams.0017_add_exams... OK
    Applying exams.0018_add_exam_types... OK
    Applying exams.0019_fill_exam_types... OK
    Applying exams.0020_source_parent_source... OK
    Applying exams.0021_exam_type_clean_up... OK
    Applying exams.0022_remove_explained_from_session... OK
    Applying exams.0023_more_question_filtering... OK
    Applying exams.0024_add_question_filter... OK
    Applying exams.0025_clean_up_session_fields... OK
    Applying exams.0026_further_session_cleanup... OK
    Applying exams.0027_session_mode... OK
    Applying exams.0028_one_to_one_parent... OK
    Applying exams.0029_question_global_sequence... OK
    Applying exams.0030_add_fields_to_revision... OK
    Applying exams.0017_add_reference_field... OK
    Applying exams.0031_merge_20170822_2057... OK
    Applying exams.0032_m2m_exam_types... OK
    Applying exams.0033_exam_exam_types... OK
    Applying exams.0034_fill_exam_exam_types... OK
    Applying exams.0035_remove_category_exam_types... OK
    Applying exams.0036_question_exam... OK
    Applying exams.0037_fill_exam... OK
    Applying exams.0038_required_question_exam... OK
    Applying exams.0039_optional_exam_types... OK
    Applying exams.0040_revision_explanation_figure... OK
    Applying exams.0031_add_credits_to_exams... OK
    Applying exams.0032_merge_20170824_0218... OK
    Applying exams.0041_merge_20170901_0933... OK
    Applying exams.0042_add_approved_by... OK
    Applying exams.0043_blank_credit... OK
    Applying exams.0044_choice_text_255_length... OK
    Applying exams.0045_rename_statuses_to_issues... OK
    Applying exams.0046_remove_complete_status... OK
    Applying exams.0047_add_incomprehensible... OK
    Applying exams.0048_incomplete_question_sessions... OK
    Applying exams.0049_answer_correction... OK
    Applying exams.0050_session_is_deleted... OK
    Applying exams.0051_highlight... OK
    Applying exams.0052_explanationrevision... OK
    Applying exams.0053_creare_explanations... OK
    Applying exams.0054_rename_explanation_fields... OK
    Applying accounts.0002_add_userena_profile... OK
    Applying exams.0055_examdate... OK
    Applying exams.0055_add_mnemonics... OK
    Applying exams.0056_merge_20171213_1242... OK
    Applying exams.0057_explanationrevision_is_contribution... OK
    Applying exams.0058_fill_explanation_is_contribution... OK
    Applying exams.0059_session_has_finished... OK
    Applying exams.0060_fill_has_finished... OK
    Applying exams.0061_exam_is_public... OK
    Applying exams.0062_skipped_and_automatic_sessions... OK
    Applying exams.0063_question_assigned_editor... OK
    Applying exams.0064_question_best_revision... OK
    Applying exams.0065_fill_best_revision... OK
    Applying exams.0066_duplicate... OK
    Applying exams.0067_duplicate_container... OK
    Applying exams.0068_create_duplicate_container... OK
    Applying exams.0069_clean_up_duplicate... OK
    Applying exams.0070_suggested_changes... OK
    Applying exams.0071_rule_is_disabled... OK
    Applying exams.0072_rule_priority... OK
    Applying exams.0073_unique_answer_per_session... OK
    Applying exams.0074_highlight_question... OK
    Applying exams.0075_fill_highlight_question... OK
    Applying exams.0076_unique_highlight_per_session... OK
    Applying exams.0077_question_is_approved... OK
    Applying exams.0078_fill_question_is_approved... OK
    Applying exams.0079_add_edited_status... OK
    Applying exams.0080_better_duplicate_options... OK
    Applying exams.0081_validate_rule_regex... OK
    Applying exams.0082_session_theme... OK
    Applying contenttypes.0002_remove_content_type_name... OK
    Applying accounts.0003_batch_complete_number... OK
    Applying accounts.0004_fill_batch_count... OK
    Applying accounts.0005_add_name_display_prefrance... OK
    Applying accounts.0006_add_fields_for_personal_email... OK
    Applying accounts.0007_profile_mangers... OK
    Applying accounts.0008_auto_20180102_1827... OK
    Applying accounts.0009_nickname_not_required... OK
    Applying accounts.0010_not_null_nickname... OK
    Applying accounts.0011_profile_primary_interest... OK
    Applying accounts.0012_improve_primary_interests... OK
    Applying accounts.0013_add_primary_interests...Traceback (most recent call last):
    File "manage.py", line 22, in <module>
        execute_from_command_line(sys.argv)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
        utility.execute()
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
        self.execute(*args, **cmd_options)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
        output = self.handle(*args, **options)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
        fake_initial=fake_initial,
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
        state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
        state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
        state = migration.apply(state, schema_editor)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
        operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
        self.code(from_state.apps, schema_editor)
    File "/Users/MSArabi/Sources/Fudulbank/accounts/migrations/0013_add_primary_interests.py", line 14, in add_primary_interests
        exam_content_type = ContentType.objects.get(app_label='exams', model='exam')
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
    File "/Users/MSArabi/Sources/Fudulbank/venv/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
        self.model._meta.object_name
    __fake__.DoesNotExist: ContentType matching query does not exist.

Changing lines 14 and 15 in `accounts/migrations/0013_add_primary_interests.py` to [use `get_or_create` instead of `get`](https://stackoverflow.com/a/31543063/6797938) fixes the above error.
However, the same issue then repeats with lines 17, 20, and 24 of the same file. I couldn't track down where the initial objects that are being referenced in these particular lines are created initially. I expected that to be a previous migration up the migration history, yet I don't think I found it.

In any case, the point is that there are model instances being referenced before being created in the database. I'm not sure how each specific error should be solved. My solution would be that either a previous migration creates the objects so that they exist by the time they are referenced or that I use `get_or_create` to avoid referencing non-existent objects.

**Comment by msarabi95** [comment]
BTW this issue has prevented me so far from completing fudul's setup, so I would be grateful if it gets resolved as soon as possible

**Comment by sul6anheart** [comment]
what the solution ?

**Comment by sul6anheart** [comment]
what the solution?

**Comment by osamak** [comment]
The issue has been just resolved in babc3b3558f887fd355f010d06e615bf7a7f77b0.
Thank you for the report!
